[build]
args_bin = []
bin = "bin/cleve serve"
cmd = "make cleve"
delay = 200
exclude_dir = ["test_data"]
exclude_regex = ["*_test.go"]
exclude_unchanged = false
include_ext = ["go", "tpl", "tmpl", "html"]
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
