[build]
args_bin = []
bin = "tmp/cleve serve"
cmd = "tailwindcss -i ./assets/css/_input.css -o ./assets/css/style.css && go build -o ./tmp/cleve ./cmd/cleve"
delay = 200
exclude_dir = ["test_data"]
exclude_regex = ["*_test.go"]
exclude_unchanged = false
include_ext = ["go", "tpl", "tmpl", "html"]
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
